set -as terminal-features ",*:RGB"
set -g base-index 1
set -g mode-keys vi
set -g status-bg black
set -g status-fg white
set -g window-status-current-style "bg=default bold"
set -g focus-events on
set -g default-shell "$SHELL"
set -g mouse on
set -g history-limit 100000
set -g set-clipboard on
set -g status-right ""

bind r source-file "~/.config/tmux/tmux.conf"

# Resize panes using Vim keys
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Switch panes using Vim keys
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
