$font = Input Mono

general {
    hide_cursor = true
}

# Leaving this here since it might be useful for laptop later
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 1, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgba(ebdbb2ee)
    check_color = rgba(98971aee) rgba(b8bb26ee) 120deg
    fail_color = rgba(cc241dee) rgba(fb4934ee) 40deg

    font_color = rgb(ebdbb2)
    fade_on_empty = true
    rounding = 100

    font_family = $font
    placeholder_text = Password, please.

    dots_spacing = 0.3

    position = 0, 100
    halign = center
    valign = bottom
}

# Time
label {
    monitor =
    text = $TIME
    font_size = 200
    font_family = $font
    color = rgb(ebdbb2)

    position = -30, 0
    halign = center
    valign = center
}
