set -a terminal-features "tmux-256color:RGB"
set -g base-index 1
set -g mode-keys vi
set -g status-justify centre
set -g status-style "bg=default"
set -g window-status-current-style "bg=default bold"
set -g status-right "%H:%M"
set -g status-interval 1
set -g focus-events on
set -g default-shell "$SHELL"

bind r source-file "~/.config/tmux/tmux.conf"

# Resize panes using Vim keys
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Switch panes using Vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

